version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile.production
    image: bedav-api
    env_file:
      - ./.env

  scripts:
    image: bedav-api
    env_file:
      - ./.env
    command: yarn scrape:prod

  website:
    build:
      context: ./
      dockerfile: ./docker/website/Dockerfile.production
    image: bedav-web
    env_file:
      - ./.env

  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./conf/nginx.proxy.conf:/etc/nginx/nginx.conf

  db:
    image: postgres
    volumes:
      - bedav-data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  bedav-data:
