FROM node:slim as build

RUN mkdir /var/app && mkdir /env
WORKDIR /var/app

COPY ./package.json ./package.json
RUN npm install

COPY ./env /env

COPY ./webpack.common.js ./webpack.common.js
COPY ./webpack.prod.js ./webpack.prod.js
COPY ./.babelrc ./.babelrc

COPY ./web ./web
COPY ./icons ./icons

RUN npm run build-prod

FROM nginx

RUN mkdir /var/app && mkdir /var/app/build
WORKDIR /var/app

COPY --from=build /var/app/dist /var/app/dist
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
