FROM node:slim as build

RUN mkdir -p /var/app/website
WORKDIR /var/app/website

COPY ./website .
COPY ./.env ../.env
RUN yarn install --frozen-lockfile

COPY ./website/icons ./icons
RUN yarn build:prod

FROM nginx

RUN mkdir -p /var/app/website
WORKDIR /var/app/website

COPY --from=build /var/app/website/dist /var/app/website/dist
COPY ./conf/nginx.website.conf /etc/nginx/nginx.conf
