FROM node:slim as build

RUN mkdir -p /var/app/website
WORKDIR /var/app/website

COPY ./website .
COPY ./.env ../.env
RUN npm ci

COPY ./website/icons ./icons
RUN npm run build-prod

FROM nginx

RUN mkdir -p /var/app/website
WORKDIR /var/app/website

COPY --from=build /var/app/website/dist /var/app/website/dist
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
