FROM node:slim as build

RUN mkdir /var/app/website
WORKDIR /var/app/website

COPY ./website .
RUN npm ci

COPY ./icons ./icons
COPY ./env /env
RUN npm run build-prod

FROM nginx

RUN mkdir /var/app && mkdir /var/app/build
WORKDIR /var/app

COPY --from=build /var/app/website/dist /var/app/dist
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
